#!/usr/bin/env python3
"""Embed agent-session highlights into public/index.html as static HTML.

The production CSP (default-src 'none') blocks all JavaScript, so the quote
stream is baked into the page at build time instead of rendered client-side.

Usage:
    scripts/embed-highlights.py [path/to/highlights.jsonl]

Defaults to ~/.claude/highlights/highlights.jsonl. Rewrites the block between
the highlights:begin / highlights:end markers in public/index.html. Only the
ts, model, and quote fields are published.
"""

import html
import json
import math
import re
import sys
from datetime import datetime
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
INDEX = REPO_ROOT / "public" / "index.html"
DEFAULT_SOURCE = Path.home() / ".claude" / "highlights" / "highlights.jsonl"

# One half of the scroll loop must be taller than any realistic viewport so
# the seamless translateY(-50%) wrap never shows a gap.
MIN_LINES_PER_HALF = 72
SECONDS_PER_LINE = 2.6

MODEL_CLASS = {"fable": "model-fable", "opus": "model-opus", "sonnet": "model-sonnet"}


def load(source: Path) -> list[dict]:
    items = []
    for line in source.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            item = json.loads(line)
        except json.JSONDecodeError:
            continue
        if all(item.get(k) for k in ("ts", "model", "quote")):
            items.append(item)
    items.sort(key=lambda i: i["ts"])
    return items


def render_line(item: dict) -> str:
    t = datetime.fromisoformat(item["ts"]).strftime("%Y-%m-%d %H:%M:%S")
    model = item["model"].removeprefix("claude-")
    cls = next(
        (c for key, c in MODEL_CLASS.items() if key in model),
        "",
    )
    model_cls = f"model {cls}".strip()
    quote = html.escape(item["quote"])
    return (
        f'<div class="stream-line"><span class="t">{t}</span> '
        f'<span class="{model_cls}">{html.escape(model)}</span>'
        f'<span class="sep"> ❯ </span>'
        f'<span class="text">{quote}</span></div>'
    )


def main() -> int:
    source = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_SOURCE
    items = load(source)
    if not items:
        print(f"No usable highlights in {source}", file=sys.stderr)
        return 1

    repeats = max(2, math.ceil(MIN_LINES_PER_HALF / len(items)))
    half = [render_line(i) for i in items] * repeats
    dur = round(len(half) * SECONDS_PER_LINE)
    indent = " " * 10
    lines = "\n".join(indent + "  " + l for l in half + half)
    block = (
        "<!-- highlights:begin — generated by scripts/embed-highlights.py; "
        "do not edit by hand -->\n"
        f'{indent}<div class="stream-scroll" style="--dur: {dur}s">\n'
        f"{lines}\n"
        f"{indent}</div>\n"
        f"{indent}<!-- highlights:end -->"
    )

    text = INDEX.read_text(encoding="utf-8")
    new_text, n = re.subn(
        r"<!-- highlights:begin.*?<!-- highlights:end -->",
        block,
        text,
        count=1,
        flags=re.DOTALL,
    )
    if n != 1:
        print(f"Markers not found in {INDEX}", file=sys.stderr)
        return 1
    INDEX.write_text(new_text, encoding="utf-8")
    print(f"Embedded {len(items)} quotes ({len(half)} lines per half, {dur}s loop)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
